image: archlinux
oauth: pages.sr.ht/PAGES:RW
sources:
  - https://github.com/swaywm/swaywm.org
packages:
  - hut
tasks:
  - build: |
      cd swaywm.org/
      curl --fail -o site/intro.webm https://l.sr.ht/lJ9C.webm
  - deploy: |
      cd swaywm.org/
      [ "$(git rev-parse origin/master)" = "$(git rev-parse HEAD)" ] || complete-build
      hut pages publish -d swaywm.org site/
