image: archlinux
oauth: pages.sr.ht/PAGES:RW
sources:
  - https://github.com/swaywm/swaywm.org
packages:
  - hut
tasks:
  - build: |
      cd swaywm.org/
      curl -o site/intro.webm https://l.sr.ht/lJ9C.webm
  - deploy: |
      [ -n "$GITHUB_PR_NUMBER" ] && complete-build
      tar -cvz -C swaywm.org/site/ . | hut pages publish -d swaywm.org /dev/stdin
